
url: http://oneslang.net/
title: oneslang
author: oneslang
keywords: go,golang,oneslang,goroutine,channel,select,interface,panic,recover
description: golang

markdown: kramdown
pygments: true

nav:
  - [golang, Golang]
  - [hadoop, Hadoop]
golang:
  - [index, 简介]
  - [env, 环境]
  - [basic, 基础]
  - [pointer, 指针]
  - [function, 函数]
  - [package, 包]
  - [interface, 接口]
  - [method, 方法]
  - [concurrency, 并发]
  - [oop, OOP]
  - [convention, 惯例]
  - [puzzle, 解惑]
  - [memo, 备忘]
  - [resource, 资源]
hadoop:
  - [index, 简介]
  - [concept, 概念]
  - [install, 安装]
  - [conf, 配置]
  - [memo, 备忘]
  - [resource, 资源]
